# Subscription configuration file for CUPS v2.4.10
# Written by cupsd
NextSubscriptionId 160
<Subscription 159>
Events printer-state-changed printer-restarted printer-shutdown printer-stopped printer-added printer-deleted job-state-changed job-created job-completed job-stopped
Owner root
Recipient dbus://
LeaseDuration 3600
Interval 0
ExpirationTime 1784966845
NextEventId 1
</Subscription>
